#!/usr/bin/env bash

set -e

sudo apt-get update && sudo apt-get dist-upgrade -y

cd /workspaces/hass-qwikswitch-api

# Install project dependencies
python3 -m pip install --requirement requirements.txt

# Aliases
echo 'alias cl="claude --dangerously-skip-permissions"' | tee -a ~/.bashrc ~/.zshrc

# Install the pre-commit hooks
pre-commit install

# Install Claude Code
curl -fsSL https://claude.ai/install.sh | bash

#mypy --install-types